# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1en1sPbLNyvdDWfreN53LFSmEVLicGZPm
"""

from lxml import html
import requests

import pandas as pd

amazon_url ='https://www.amazon.in/OnePlus-Mirror-Black-128GB-Storage/product-reviews/B07DJD1Y3Q/ref=cm_cr_getr_d_paging_btm_next_8?ie=UTF8&reviewerType=all_reviews&pageNumber=8'

user_agent ='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36'

headers = {'User-Agent': user_agent}
page = requests.get(amazon_url, headers = headers)
parser = html.fromstring(page.content)

xpath_reviews = '//div[@data-hook="review"]'
reviews = parser.xpath(xpath_reviews)
reviews[3].xpath('.//span[@data-hook="review-body"]//text()')[1:4]

xpath_rating  = './/i[@data-hook=\"review-star-rating\"]//text()'
xpath_title   = './/a[@data-hook="review-title"]//text()'
xpath_date    = './/span[@data-hook="review-date"]//text()'
xpath_body    = './/span[@data-hook="review-body"]//text()'
xpath_helpful = './/span[@data-hook="helpful-vote-statement"]//text()'

reviews_df=pd.DataFrame()
for review in reviews:
    rating  = review.xpath(xpath_rating)
    title   = review.xpath(xpath_title)[1]
    date    = review.xpath(xpath_date)
    body    = review.xpath(xpath_body)
    helpful = review.xpath(xpath_helpful)
    

    review_dict = {'rating': rating,
                   'title': title,            
                   'date': date,
                   'body': body[1:len(body)-1],
                   'helpful': helpful}
    reviews_df = reviews_df.append(review_dict, ignore_index=True)

reviews_df

reviews_df['title']

reviews_df.to_csv("reviews3.csv",index=False)

